# Generated by Django 3.0.8 on 2020-07-20 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('create_date', models.DateTimeField(verbose_name='Дата создания')),
                ('files', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_desc', models.TextField(max_length=600)),
                ('priority', models.CharField(choices=[('Низ', 'Низкий'), ('Ср', 'Средний'), ('Вс', 'Высокий')], max_length=50)),
                ('create_date', models.DateTimeField(verbose_name='Дата создания')),
                ('work_date', models.DateTimeField(verbose_name='Дата исполнения')),
                ('status', models.CharField(choices=[('Вп', 'Выполнена'), ('Нв', 'Не выполнена')], max_length=50)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crmServer.Case')),
                ('user_cr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_wr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_workmen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
