# Generated by Django 3.0.8 on 2020-07-20 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='case',
        ),
        migrations.AddField(
            model_name='task',
            name='case',
            field=models.ManyToManyField(to='crmServer.Case'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_cr',
        ),
        migrations.AddField(
            model_name='task',
            name='user_cr',
            field=models.ManyToManyField(related_name='user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_wr',
        ),
        migrations.AddField(
            model_name='task',
            name='user_wr',
            field=models.ManyToManyField(related_name='user_workmen', to=settings.AUTH_USER_MODEL),
        ),
    ]
