# Generated by Django 3.0.8 on 2020-07-20 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmServer', '0002_auto_20200720_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='case',
        ),
        migrations.AddField(
            model_name='task',
            name='case',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crmServer.Case'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_cr',
        ),
        migrations.AddField(
            model_name='task',
            name='user_cr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_wr',
        ),
        migrations.AddField(
            model_name='task',
            name='user_wr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_workmen', to=settings.AUTH_USER_MODEL),
        ),
    ]
