# Generated by Django 3.0.8 on 2020-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmServer', '0003_auto_20200720_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='create_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Не выполнена', 'Не выполнена')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_date',
            field=models.DateField(verbose_name='Дата исполнения'),
        ),
    ]
